server:
  port: 10001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      trace:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

user:
  id: 1
  name: xuliang
  age: 24
  sex: 男
